name: Second-Workflow
on: workflow_dispatch
jobs:
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: welcom the owner
        run: echo "Welcome Manunath"
      - name: This is Github Actions
        run: echo "Thsis is GitHub Actions"
      
